[package]
name = "uwu-tray"
version = "0.1.0"
authors = ["Catherine Gilbert <catherine.gilbert15@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uwuify = "0.1.0"
tray-item = "0.4.0-alpha"
clipboard = "0.5.0"

[target.'cfg(windows)'.build-dependencies]
windres = "0.2.2"